### ISSUE TITLE
Remove close ( X ) option from default 6 segments 

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#160]
**Woo Commerce Version** - 8.0.2
**WordPress Version** - 6.3
**Plugin Version** - 1.9.0
**Description** - Remove close ( X ) option from default 6 segments 

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/3d6c0a78-c968-44a0-8efc-5cae43805294)

**Comment by navneet-cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Still Exists when user create new Segment...

https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/c337b904-dad3-40a4-b688-dc050b1c7b94

**Comment by navneet-cedcoss** [comment]
When segment count is more than 6, then cross symbol is shown for all except first one

**Comment by ashish-wps** [comment]
Okay
