### ISSUE TITLE
When user add membership product in cart so membership discount apply on apply points

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/points-and-rewards-for-woocommerce#187]
**Woo Commerce Version - 8.5.2
WordPress Version - 6.4.3
Plugin Version - 2.1.2
Description -** When user add membership product in cart so membership discount apply on apply points

[scrnli_12_02_2024_12-13-51.webm](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/d96ee146-3188-48ae-9560-21be0ccbaa9d)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
**Still Exist 

With Membership**

![image](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/51ed842a-0f5c-41bb-986a-7de36173eff6)

**Without Membership**

![Screenshot from 2024-02-16 17-22-15](https://github.com/wpswings/points-and-rewards-for-woocommerce/assets/105413021/2558aeb9-ec4e-4477-ac8b-5e8afe89e1e7)

**Comment by navneet-cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed
